/* eslint-disable prettier/prettier */
/* eslint-disable no-unused-vars */
import { StyleSheet, Dimensions } from 'react-native';
import Constants from '../../Helpers/constant';

const width = Dimensions.get('window').width;
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Constants.white,
    paddingTop: 10,
  },
  center: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  profileMainView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 20,
    paddingHorizontal: 10,
  },

  labels: {
    position: 'absolute',
    top: -13,
    left: 20,
    backgroundColor: Constants.white,
    color: Constants.black,
    padding: 2,
    borderWidth: 1,
    borderColor: Constants.red,
    borderRadius: 20,
    paddingHorizontal: 5,
  },

  profileView: {
    backgroundColor: '#FDEDEB',
    height: 50,
    width: 50,
    borderRadius: 25,
  },
  mapView: {
    borderRadius: 20,
    // height: (Dimensions.get('screen').height / 100) * 55,
    width: Dimensions.get('screen').width,
    position: 'relative',
    overflow: 'hidden',
    flex: 1,
  },
  mapOrigin: {
    // height: (Dimensions.get('screen').height / 100) * 55,
    flex: 1,
    width: Dimensions.get('screen').width,
  },
  startField: {
    borderColor: Constants.yellow,
    borderWidth: 1,
    borderRadius: 25,
    backgroundColor: '#FFDEAB',
    flexDirection: 'row',
    paddingHorizontal: 20,
    justifyContent: 'space-between',
    alignItems: 'center',
    zIndex: 9,
  },
  endField: {
    borderColor: '#8BFF63',
    borderWidth: 1,
    borderRadius: 25,
    backgroundColor: '#E8FFE0',
    flexDirection: 'row',
    paddingHorizontal: 20,
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 10,
    zIndex: 8,
  },
  fieldView: {
    position: 'absolute',
    width: '100%',
    padding: 10,
    paddingHorizontal: 30,
  },
  plusBtn: {
    backgroundColor: Constants.red,
    padding: 5,
    borderRadius: 25,
    marginRight: -10,
    marginTop: 10,
  },
  swtichBtn: {
    flexDirection: 'row',
    backgroundColor: Constants.red,
    paddingVertical: 10,
    paddingHorizontal: 10,
    // width: 150,
    borderRadius: 12,
    justifyContent: 'center',
  },
  swtichBtn2: {
    flexDirection: 'row',
    borderColor: Constants.red,
    borderWidth: 2,
    backgroundColor: Constants.white,
    padding: 15,
    width: 180,
    borderRadius: 18,
    justifyContent: 'center',
  },
  itemdetail: {
    color: Constants.white,
    fontWeight: '700',
    fontSize: 22,
    textAlign: 'center',
    marginTop: 10,
    fontFamily: 'Helvetica',
  },
  normalField: {
    borderColor: Constants.red,
    borderWidth: 1,
    borderRadius: 25,
    backgroundColor: Constants.white,
    flexDirection: 'row',
    paddingHorizontal: 20,
    justifyContent: 'space-between',
    alignItems: 'center',
    color: Constants.black,
    position: 'relative',
    minHeight: 50
  },

  normalField2: {
    borderColor: Constants.yellow,
    borderWidth: 2,
    borderRadius: 25,
    backgroundColor: Constants.white,
    flexDirection: 'row',
    paddingHorizontal: 10,
    justifyContent: 'space-between',
    alignItems: 'center',
    height: 40,
  },
  mainBg: {
    flex: 1,
    backgroundColor: Constants.pink,
    // borderTopRightRadius: 40,
    // borderTopLeftRadius: 40,
    marginTop: 10,
    borderRadius: 20,
    // borderTopLeftRadius: 20,
    // borderTopRightRadius: 20,
    // paddingVertical: 20,
    paddingHorizontal: 20,
  },
  cardView: {
    borderRadius: 20,
    overflow: 'hidden',
    marginVertical: 2,
  },
  card: {
    width: Dimensions.get('screen').width - 40,
    // backgroundColor: Constants.white,
    padding: 20,
    position: 'relative',
  },
  reportBtn: {
    position: 'absolute',
    right: 5,
    top: 2,
    backgroundColor: Constants.white,
    padding: 10,
    borderRadius: 10,
    zIndex: 9
  },
  reportBtntxt: {
    fontWeight: '700',
    color: Constants.red,
    textAlign: 'center',
    fontSize: 14,
    fontFamily: 'Helvetica',

  },
  subCard: {
    flexDirection: 'row',
    // backgroundColor: Constants.red,
    padding: 10,
    borderRadius: 15,
  },
  itemName: {
    color: Constants.white,
    fontSize: 16,
    fontWeight: '700',
    fontFamily: 'Helvetica',

  },
  from: {
    color: Constants.white,
    fontWeight: '600',
    fontSize: 13,
    textAlign: 'right',
    fontFamily: 'Helvetica',
  },
  to: {
    color: Constants.white,
    fontWeight: '600',
    fontSize: 13,
    textAlign: 'left',
    fontFamily: 'Helvetica',
  },
  noticard: {
    width: Dimensions.get('screen').width - 40,
    backgroundColor: Constants.red,
    padding: 20,
    borderRadius: 20,
    marginVertical: 10,
  },

  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 22,
    backgroundColor: '#rgba(0, 0, 0, 0.5)',
  },
  modalView: {
    margin: 20,
    backgroundColor: 'white',
    borderRadius: 10,
    padding: 35,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  modalView2: {
    // margin: 20,
    backgroundColor: 'transparent',
    borderRadius: 10,
    // padding: 35,
    alignItems: 'center',
    gap: 5,
    flexDirection: 'row',
  },
  iconViewStyle: {
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    backgroundColor: Constants.red,
  },
  textStyle: {
    color: Constants.black,
    fontWeight: 'bold',
    textAlign: 'center',
    // fontFamily: 'Helvetica',
    fontSize: 16,
    fontFamily: 'Helvetica',
  },
  modalText: {
    color: Constants.white,
    fontWeight: 'bold',
    textAlign: 'center',
    fontFamily: 'Helvetica',
    fontSize: 14,
  },
  cancelAndLogoutButtonWrapStyle: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
  },
  cancelButtonStyle: {
    flex: 0.5,
    backgroundColor: Constants.black,
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    marginRight: 15,
  },

  supportOptButton: {
    // flex: 0.5,
    // backgroundColor: Constants.black,
    borderRadius: 20,
    alignItems: 'center',
    paddingVertical: 10,
    // marginRight: 15,
    // borderWidth: 1,
    // borderColor: Constants.grey,
    flexDirection: 'row',
    justifyContent: 'flex-start',
    paddingHorizontal: 10,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,

    elevation: 3,
  },
  logOutButtonStyle: {
    flex: 0.5,
    backgroundColor: Constants.red,
    borderRadius: 5,
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 15,
  },
  showdetail: {
    color: Constants.red,
    textAlign: 'center',
    fontSize: 12,
    fontWeight: '700',
    fontFamily: 'Helvetica',
  },
  chatHeading: {
    width: '100%',
    textAlign: 'center',
    fontSize: 15,
    color: Constants.black,
    marginTop: 5,
    fontWeight: 'bold',
    fontFamily: 'Helvetica',
  },
  chatContainer: {
    width: '100%',
    minHeight: '50%',
  },
  ChitCountainer: {
    backgroundColor: '#DF0707',
    // display:'flex',
    // flexDirection:'row',
    marginTop: 2,
    marginBottom: 5,
    position: 'relative',
    paddingVertical: 20,
    paddingHorizontal: 10,
    borderRadius: 10,
  },
  acceptButton: {
    fontSize: 17,
    borderRadius: 13,
    textAlign: 'center',
    fontWeight: 'bold',
    fontFamily: 'Dpdorkdiary',

  },
  rejectButton: {
    fontSize: 17,
    color: 'white',
    borderRadius: 13,
    textAlign: 'center',
    fontWeight: 'bold',
    fontFamily: 'Dpdorkdiary',

  },
  chitText: {
    color: Constants.black,
    fontSize: 18,
    marginTop: 5,
    marginBottom: 5,
    fontWeight: '600',
    fontFamily: 'Helvetica',
  },
  chatDuration: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    fontFamily: 'Helvetica',
  },

  //dropdown

  containers: {
    backgroundColor: 'white',
    padding: 16,
  },
  dropdown: {
    height: 50,
    borderColor: Constants.red,
    borderWidth: 1,
    borderRadius: 25,
    paddingHorizontal: 20,
    width: '100%',
    alignSelf: 'center',
    marginTop: 10,
    backgroundColor: Constants.white,
    color: Constants.black,
  },
  icon: {
    marginRight: 5,
    color: Constants.black,
  },
  label: {
    color: Constants.black,
    position: 'absolute',
    backgroundColor: 'white',
    left: 22,
    top: 8,
    zIndex: 999,
    paddingHorizontal: 8,
    fontSize: 14,
  },
  placeholderStyle: {
    color: Constants.black,
    fontSize: 16,
  },
  selectedTextStyle: {
    color: Constants.black,
    fontSize: 16,
  },
  iconStyle: {
    // color: Constants.black,
    width: 20,
    height: 20,
  },
  inputSearchStyle: {
    color: Constants.black,
    height: 40,
    fontSize: 16,
  },

  postjobView3: {
    borderWidth: 2,
    borderColor: Constants.grey,
    borderRadius: 15,
    padding: 20,
    marginVertical: 15,
    position: 'relative',
  },
  selectjobname: {
    borderWidth: 2,
    borderColor: Constants.grey,
    borderRadius: 15,
    paddingleft: 15,
    marginBottom: 15,
    justifyContent: 'center',
  },
  showAmount: {
    color: Constants.red,
    fontSize: 26,
    fontWeight: '700',
    fontFamily: 'Helvetica',
  },
  description: {
    fontSize: 11,
    fontWeight: '500',
    fontFamily: 'Helvetica',
    color: Constants.white,
    lineHeight: 15,
    marginTop: 5,
  },
  listtypeName: {
    fontSize: 20,
    fontWeight: '700',
    fontFamily: 'Helvetica',
    color: Constants.white,
  },

  applyBtn: {
    backgroundColor: Constants.red,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    width: '90%',
    borderColor: 'rgba(51, 51, 51, 0.6)',
    borderWidth: 3,
  },
  applyBtnTxt: {
    color: Constants.white,
    fontWeight: '700',
    fontFamily: 'Helvetica',
    fontSize: 12,

    lineHeight: 18,
  },
  chatImage: {
    height: 50,
    width: 50,
    borderRadius: 100,
  },

  //profile page
  supportImg: {
    height: 50,
    width: 50,
    // position: 'absolute',
    right: 0,
    top: 15,
    zIndex: 9,
  },
  userIdText: {
    textAlign: 'center',
    fontSize: 18,
    fontWeight: '700',
    color: Constants.black,
    // marginTop: 10,
    // position: 'absolute',
    // left: 20,
    fontFamily: 'Helvetica',
  },
  userNameView: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  userNameText: {
    textAlign: 'center',
    fontSize: 24,
    fontWeight: '700',
    color: Constants.black,
    marginTop: 30,
    fontFamily: 'Helvetica',
  },

  //home page
  startMarkerView: {
    height: 30,
    width: 30,
    borderRadius: 15,
    backgroundColor: '#FFDEAB',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 3,
    borderColor: Constants.yellow,
    position: 'relative',
  },


});

export default styles;
